name: kafka-cart

services:
  kafka:
    container_name: kafka
    image: apache/kafka:latest
    ports:
      - "9092:9092"
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: my_app
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"